// ******************************************************
// DO NOT CHANGE THE CONTENT OF THIS FILE
// This file was generated by the T4 engine and the 
// contents of this source code will be changed after
// the custom tool was run.
// ******************************************************
using BlogSytemManager.Application;
using BlogSytemManager.DomainObject;
using BlogSytemManager.DomainObject._PageOfItems;
using BlogSytemManager.IService;
using BolgSytemManager.Domain.Model;
using BlogSytemManager.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.Text;
using System.Xml.Linq;


namespace BlogSytemManager.Service
{
    // 注意: 使用“重构”菜单上的“重命名”命令，可以同时更改代码、svc 和配置文件中的类名“Service1”。
    // 注意: 为了启动 WCF 测试客户端以测试此服务，请在解决方案资源管理器中选择 Service1.svc 或 Service1.svc.cs，然后开始调试。

    //WCF服务实现代码修改如下，为了在客户端显示服务端发生的异常信息，在服务实现类添加[ServiceBehavior(IncludeExceptionDetailInFaults = true)]特性：
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.PerSession,IncludeExceptionDetailInFaults = true)]

public partial class RoleService : IRoleService
   {
		  private readonly IRoleService roleserviceImpl = new RoleServiceImpl();
				public RoleObject[] GetAllRole()
		{
		return roleserviceImpl.GetAllRole();
		}
		public RoleObject GetRoleById(Object id)
		{
		return roleserviceImpl.GetRoleById(id);
		}
		public RoleObjectPageOfItems GetRolepageOfitems(Int32 pageIndex, Int32 pageSize, RoleObjectPageOfItems pageofitems)
		{
		return roleserviceImpl.GetRolepageOfitems(pageIndex, pageSize, pageofitems);
		}
		public Boolean DeleteRoleById(Object id)
		{
		return roleserviceImpl.DeleteRoleById(id);
		}
		public Boolean DeleteRoles(String[] ids)
		{
		return roleserviceImpl.DeleteRoles(ids);
		}
		public Boolean UpdateRole(RoleObject obj)
		{
		return roleserviceImpl.UpdateRole(obj);
		}
		public Boolean UpdateRoles(RoleObject[] objs)
		{
		return roleserviceImpl.UpdateRoles(objs);
		}
        public RoleObject CreateRole(RoleObject obj)
		{
		return roleserviceImpl.CreateRole(obj);
		}
		public void Dispose() { roleserviceImpl.Dispose(); }
	}
}


