//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_02_事物的使用
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
