// <auto-generated />
namespace BlogSytemManager.Repository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddFnIsPaid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFnIsPaid));
        
        string IMigrationMetadata.Id
        {
            get { return "201512300200143_AddFnIsPaid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
