//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 并行编程.EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int ID { get; set; }
        public string Menu_Name { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool Status { get; set; }
        public int Role_ID { get; set; }
    }
}
