// ******************************************************
// DO NOT CHANGE THE CONTENT OF THIS FILE
// This file was generated by the T4 engine and the 
// contents of this source code will be changed after
// the custom tool was run.
// ******************************************************
using AutoMapper;
using AutoMapper.QueryableExtensions;
using BlogSytemManager.DomainObject;
using BlogSytemManager.DomainObject._PageOfItems;
using BlogSytemManager.Infrastructure.ExpressionHelper;
using BlogSytemManager.IService;
using BlogSytemManager.Repository.Repositories;
using BolgSytemManager.Domain.IRepositories;
using BolgSytemManager.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;


namespace BlogSytemManager.Application
{

public partial class ActionInfoServiceImpl : ApplicationServiceImpl<ActionInfoObject, ActionInfo>, IActionInfoService
   {
		 private static IActionInfoRepository actionInfoRepository = new ActionInfoRepository();

        public ActionInfoServiceImpl()
            : base(actionInfoRepository)
        {

        }

				public ActionInfoObject[] GetAllActionInfo()
		{
	return base.GetAllDataObject();
		}
		public ActionInfoObject GetActionInfoById(Object id)
		{
	return base.GetDataObjectById(id);
		}
		public Boolean DeleteActionInfoById(Object id)
		{
	return base.DeleteDataObjectById(id);
		}
		public Boolean DeleteActionInfos(String[] ids)
		{
	return base.DeleteDataObjects(ids);
		}
		public Boolean UpdateActionInfo(ActionInfoObject obj)
		{
	return base.UpdateDataObject(obj);
		}
		public Boolean UpdateActionInfos(ActionInfoObject[] objs)
		{
	return base.UpdateDataObjects(objs);
		}
        public ActionInfoObject CreateActionInfo(ActionInfoObject obj)
		{
	return base.CreateDataObject(obj);
		}
	}
}


