// ******************************************************
// DO NOT CHANGE THE CONTENT OF THIS FILE
// This file was generated by the T4 engine and the 
// contents of this source code will be changed after
// the custom tool was run.
// ******************************************************
using AutoMapper;
using AutoMapper.QueryableExtensions;
using BlogSytemManager.DomainObject;
using BlogSytemManager.DomainObject._PageOfItems;
using BlogSytemManager.Infrastructure.ExpressionHelper;
using BlogSytemManager.IService;
using BlogSytemManager.Repository.Repositories;
using BolgSytemManager.Domain.IRepositories;
using BolgSytemManager.Domain.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;


namespace BlogSytemManager.Application
{

    public partial class MenuServiceImpl : ApplicationServiceImpl<MenuObject, Menu>, IMenuService
    {
        private static IMenuRepository menuRepository = new MenuRepository();

        public MenuServiceImpl()
            : base(menuRepository)
        {

        }

        public MenuObject[] GetAllMenu()
        {
            return base.GetAllDataObject();
        }
        public MenuObject GetMenuById(Object id)
        {
            return base.GetDataObjectById(id);
        }
        public Boolean DeleteMenuById(Object id)
        {
            return base.DeleteDataObjectById(id);
        }
        public Boolean DeleteMenus(String[] ids)
        {
            return base.DeleteDataObjects(ids);
        }
        public Boolean UpdateMenu(MenuObject obj)
        {
            return base.UpdateDataObject(obj);
        }
        public Boolean UpdateMenus(MenuObject[] objs)
        {
            return base.UpdateDataObjects(objs);
        }
        public MenuObject CreateMenu(MenuObject obj)
        {
            return base.CreateDataObject(obj);
        }
    }
}


